# Generated by Django 4.0.3 on 2022-03-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
