# Generated by Django 4.0.3 on 2022-03-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_userdb_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdb',
            name='id',
        ),
        migrations.AlterField(
            model_name='userdb',
            name='email',
            field=models.CharField(max_length=250, primary_key=True, serialize=False),
        ),
    ]
